### ISSUE TITLE
LoadSpaceMathPackage

### ISSUE THREAD

**Issue by tvalencia** [spacemathproject/SpaceMath#9]
![LoadSpaceMath](https://user-images.githubusercontent.com/53123066/88470254-ebe5c200-cebf-11ea-8a5d-81c1d3b0ab69.png)

**Comment by vsht** [comment]
Indeed, since there is no wiki and no mailing list, this looks a bit weird. Probably an artefact of
of doing `/s/FeynCalc/SpaceMath/` and `/s/FC/SM/` on
https://github.com/FeynCalc/feyncalc/blob/master/FeynCalc/FeynCalc.m

Some sort of acknowledgement would have been nice, though. At least to comply
with GPLv3.

**Comment by tvalencia** [comment]
Dear Vladyslav Shtabovenko

You are right that we have not yet cited FeynCalc. This is a beta version for testing only but we are working on a full version of this package where it will be properly cited.  Thank you for your comments.

**Comment by vsht** [comment]
Dear tvalencia,

to avoid any misinterpretations, let me state that
the FeynCalc package is open source under a copyleft
license (GPLv3). Essentially, this means that GPL-covered
code can be reused in multiple ways as long as
the authors of the original code are acknoweldged
and the resulting code is also licensed under the GPL.

An acknowledgement in the sense of GPL is usually added to the source
code files e.g. as in 

https://github.com/effExTeam/CoDEx-1.0.0/blob/master/install.m#L22

Otherwise, if a source file contains no licensing information,
then all the code there is by default attributed to the
respective author(s). However, when such files contain GPL'd
code from other sources, this creates a lot of confusion and makes
it difficult to distinguish new code from the code adopted from elsewhere.
This is actually the only thing I consider important here and is 
the main reason for my request. 

So I'm only asking to properly attribute the respective codeblocks
which were obviously forked from the FeynCalc codebase. Then the
GPL conditions are satisfied and there is no issue from my side.

GPL says nothing about academic acknowledgements and
what people cite or not cite in their papers is none of
my concern. So when someone just employs FeynCalc or gets
some inspirations from it but doesn't feel like citing the
package, I normally just let it be.

If you say that the final version will have appropriate 
acknowledgements in the code, this is sufficient for me.
Thanks for your prompt and friendly reply.

Cheers,
Vladyslav

**Comment by tvalencia** [comment]
Dear vsht,

We regret this misunderstanding and reiterate that you will be properly cited and we have added the corresponding credits to our installation file according to your suggestion. 
Finally, we appreciate your comments and suggestions.

Cheers,
T. Valencia
